title: BFC
description: A Brainf**k compiler
summary: "Compiling BrainF**k to rust and the binary using rust"
subLinks:
- href: https://github.com/laspruca/bfc
  text: GitHub Repo
- href: https://crates.io/crates/bf-compile
  text: Crates.io page
date: 2021-05-21