title: BF in Rosetta
description: Brainf**k in many langauges
summary: "Implementing a BrainF**k interperter in too many languages"
subLinks:
- href: https://github.com/fallstop/bf-in-rosetta
  text: GitHub Repo
date: 2021-01-04
